# Generated by Django 5.2 on 2025-04-08 12:24

import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "permissions",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("UserScreenShare", "Screen Share"),
                            ("UserVideo", "Video"),
                            ("UserAudio", "Audio"),
                            ("UserChat", "Chat"),
                            ("UserRaiseHand", "Raise Hand"),
                            ("UserWhiteboard", "Whiteboard"),
                            ("UserPoll", "Poll"),
                            ("UserBreakoutRoom", "Breakout Room"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[("Public", "Public"), ("Private", "Private")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
            },
        ),
    ]
